image: node:14 

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm start
        artifacts:
          - dist/**  
  
  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          script:
           - npm install
           - npm run build
           - npm start